---
title: Cello
timezone: Europe/Stockholm
collections:
  cellos:
    title: Cellos
    output: true
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  violins:
    title: Violins
    output: true
    permalink: "/:collection/:name"
defaults:
- scope:
    path: ''
    type: '["cellos", "violins"]'
  values:
    image:
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl:
url:
twitter_username:
github_username:
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "cellos"
    values:
      images: []
