---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: images
  label: Images
  type: image_gallery
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- name: position
  label: Position
  type: text
  hidden: false
  default: ''
- name: Category
  label: Category
  type: text
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: category
- name: Swedish title
  label: Swedish title
  type: text
  hidden: false
  default: 
- name: Swedish description
  label: Swedish description
  type: text
  hidden: false
  default: 
- name: image
  label: Image
  type: text
  hidden: false
  default: 
pages:
- _products/violins/vio-2.md
- _products/violins.markdown
- _products/cellos.markdown
- _products/violins/french-violin-by-georges-apparut.markdown
- _products/cellos/french-cello-thouvenel-1830.markdown
